# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.cache/wt [current_project]
set_property parent.project_path C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Audio_Capture.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Background_corridor_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Background_corridor_trapdooropen_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Display.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Glassstillok_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Guardkills_hero21_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Imagewithstuff_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Display.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Vol.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/coordinates.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/corridor.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/fight.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/glass.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/glassminorcracks_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/handcuff.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/handcuff1.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/handcuff2.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/handcuff3.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/handcuffs.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/healthdown_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/imports/visha/koscreen_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/maincharacter_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/menu.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/menu1_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/menu2_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/menu3_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/menu_sprite.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/peaking_algorithm.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/pulse.v
  {C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/imports/visha/Desktop/Corridor game/rooftop_sprite.v}
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/smithereens_sprite.v
  {C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/imports/visha/Desktop/Corridor game/spideypunch_sprite.v}
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/state_ctrl.v
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/timers.v
  {C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/imports/visha/Desktop/Corridor game/truespiderman_sprite.v}
  {C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/imports/visha/Desktop/Corridor game/truevenom_sprite.v}
  {C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/imports/visha/Desktop/Corridor game/venompunch_sprite.v}
  C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/sources_1/new/Top_Student.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/arv19/Downloads/newfileat452pm.xpr/SoundDisplay/SoundDisplay.srcs/constrs_1/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
